language: cpp
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install scilab libopencv-dev 
script:
  - scilab-cli -e 'result = exec("builder.sce", "errcatch"); exit(result)'
